# docker/Dockerfile.wagtail
FROM python:3.12-slim AS wagtail-base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app/cplans

RUN apt-get update \
    && apt-get install -y build-essential libpq-dev curl \
    && apt-get clean

RUN pip install --upgrade pip && pip install -r requirements.txt


CMD ["sh"]
