# Generated by Django 5.2.4 on 2025-07-04 15:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blogger_photo',
            field=models.ForeignKey(blank=True, help_text='Photo of the blogger for the landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='landing_text',
            field=wagtail.fields.RichTextField(default='', help_text='Landing page text with full rich text support.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_heading',
            field=models.CharField(default='test', help_text='Main heading (h1) for the landing page.', max_length=255),
            preserve_default=False,
        ),
    ]
